<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Meus Pontos | Lista</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-lg-12">
                        <form role="form" class="form-horizontal">
                            <div class="form-group col-md-4">
                                <label class="col-md-2">M&ecirc;s</label>
                                <div class="col-md-10">
                                    <select class="form-control">
<?php
    $meses = array('Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez');
    foreach($meses as $key=>$mes){
?>
                                        <option value="<?=($key+1);?>"><?=$mes;?></option>
<?php
    }
?>    
                                    </select>
                                </div>    
                            </div>

                            <div class="form-group col-md-4">
                                <label class="col-md-2">Ano</label>
                                <div class="col-md-10">
                                    <select class="form-control">
    <?php
        for($ano = date('Y'); $ano >= 2000; $ano--){
    ?>
                                        <option value="<?=$ano;?>"><?=$ano;?></option>
    <?php
        }
    ?>    
                                    </select>
                                </div>    
                            </div>    

                            <div class="form-group col-md-4">
                                <div class="col-md-12"><button type="submit" class="btn btn-primary">Enviar</button></div>
                            </div>
                        </form> 
                    </div>    
                    <div class="col-lg-12 table-responsive">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-pontos">
                                <thead>
                                    <tr>
                                        <th>Data</th>
                                        <th>Entrada</th>
                                        <th>Sa&iacute;da</th>
                                        <th>Entrada</th>
                                        <th>Sa&iacute;da</th>
                                        <th>Total</th>
                                        <th>Saldo</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                        
                                        $date_begin = new DateTime('2015-07-31');
                                        $date_end = new DateTime('2015-09-01');
                                        $interval = new DateInterval('P1D');
                                        $period = new DatePeriod($date_begin, $interval, $date_end);

                                        foreach($period as $date)
                                        {
                                            if(date('w', strtotime($date->format("Y/m/d"))) > 0 && date('w', strtotime($date->format("Y/m/d"))) < 6 ){
                                                echo '
                                                <tr>
                                                    <td>'.$date->format("d/m/Y").'</td>
                                                    <td>07:45:00</td>
                                                    <td>12:00:05</td>
                                                    <td>13:30:00</td>
                                                    <td>18:00:00</td>
                                                    <td>08:45</td>
                                                    <td>00:00</td>
                                                </tr>';
                                            }    
                                        }
                                    ?>
                                     
                                </tbody>
                            </table>
                        </div>    
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.col-lg-12 (nested) -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.panel-body -->
    </div>
</div>    